### PR TITLE
fix: match remote tracking branches in ignore pattern

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by Scrum** [comment]
@marionebl ping

**Comment by marionebl** [comment]
@GitScrum Looks good, thank you! Could you change the commit message to `fix: match remote tracking branches in ignore pattern`. Please include the changes of #6 here in the commit here, too.

**Comment by Scrum** [comment]
@marionebl done.

**Comment by marionebl** [comment]
Released as `0.4.1`:

```
❯ npm show conventional-changelog-lint-config-angular .version
0.4.1
```

**Pull request merged**
